# Generated by Django 2.2.4 on 2020-05-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
