# Generated by Django 2.2.4 on 2020-05-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('uusername', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
